import guerreiroImage from './assets/guerreiro.webp'
import barbaroImage from './assets/barbaro.webp'
import bardoImage from './assets/bardo.webp'
import bucaneiroImage from './assets/bucaneiro.webp'
import cacadorImage from './assets/cacador.webp'
import cavaleiroImage from './assets/cavaleiro.webp'
import clerigoImage from './assets/clerigo.webp'
import druidaImage from './assets/druida.webp'
import arcanistaImage from './assets/arcanista.webp'
import inventorImage from './assets/inventor.webp'
import ladinoImage from './assets/ladino.webp'
import lutadorImage from './assets/lutador.webp'
import nobreImage from './assets/nobre.webp'
import paladinoImage from './assets/paladino.webp'
import samuraiImage from './assets/samurai.webp'
import soldadoImage from './assets/soldado.webp'
import magoImage from './assets/mago.webp'
import feiticeiroImage from './assets/feiticeiro.webp'
import bruxoImage from './assets/bruxo.webp'
import medicoImage from './assets/medico.webp'
import misticoImage from './assets/mistico.webp'
import pirataImage from './assets/pirata.webp'
import treinadorImage from './assets/treinador.webp'
import fradeImage from './assets/frade.webp'
import necromanteImage from './assets/necromante.webp'
import machadoPedraImage from './assets/machado-pedra.webp'
import magimarcialistaImage from './assets/magimarcialista.webp'
import duelistaImage from './assets/duelista.webp'
import seteiroImage from './assets/seteiro.webp'
import vassaloImage from './assets/vassalo.webp'
import usurpadorImage from './assets/usurpador.webp'
import ermitaoImage from './assets/ermitao.webp'

const generated = { guerreiro: guerreiroImage, barbaro: barbaroImage, bardo: bardoImage, bucaneiro: bucaneiroImage, cacador: cacadorImage, cavaleiro: cavaleiroImage, clerigo: clerigoImage, druida: druidaImage, arcanista: arcanistaImage, inventor: inventorImage, ladino: ladinoImage, lutador: lutadorImage, nobre: nobreImage, paladino: paladinoImage, samurai: samuraiImage, soldado: soldadoImage, mago: magoImage, feiticeiro: feiticeiroImage, bruxo: bruxoImage, medico: medicoImage, místico: misticoImage, pirata: pirataImage, treinador: treinadorImage, frade: fradeImage, necromante: necromanteImage, 'machado-pedra': machadoPedraImage, magimarcialista: magimarcialistaImage, duelista: duelistaImage, seteiro: seteiroImage, vassalo: vassaloImage, usurpador: usurpadorImage, ermitao: ermitaoImage }
const fallbackPalettes = {
  ladino:['#15242a','#071012','#d2a15a'],lutador:['#3b2118','#120b08','#ebae59'],nobre:['#36212d','#120d12','#dbb56c'],paladino:['#3d3217','#12100a','#fff0a1'],samurai:['#421f1e','#13090a','#e1a45d'],soldado:['#293128','#0c100b','#d5ab65'],mago:['#1f2444','#080a18','#a9bcff'],feiticeiro:['#3c1831','#140713','#ef8a88'],bruxo:['#16372c','#07120d','#86e699'],medico:['#29333a','#0a1012','#d3c3a4'],místico:['#282143','#0e0a18','#bda5ff'],pirata:['#153442','#071014','#e5b55b'],
  treinador:['#2b3a2f','#0a0f0b','#d8b45e'],frade:['#3a3628','#0f0e09','#e8d9a0'],necromante:['#1c2e2a','#060d0a','#8fe6a8'],'machado-pedra':['#382a20','#0f0b07','#e0a45f'],magimarcialista:['#2f2440','#0d0914','#c9a0e8'],duelista:['#202f3f','#0a0f14','#8fd0e8'],seteiro:['#2c3524','#0c0f08','#b8d88f'],vassalo:['#303a44','#0c0f12','#c9d4e0'],usurpador:['#33202e','#0f090d','#e896c0'],ermitao:['#2b3a26','#0b0f08','#a8d88f'],inovador:['#2a3a44','#0a0f14','#8fd0e0'],alquimista:['#38261f','#100b08','#e0a45f'],ventanista:['#243544','#090e12','#a8dce8'],atleta:['#3a2418','#100a06','#e89a5f'],burgues:['#38301f','#100e08','#e0cf8f'],santo:['#3a3320','#100e08','#ffe9a8'],sentinela:['#24305e','#0a0e1a','#8fa8e8'],miragem:['#38301f','#100e08','#e0c08f'],cruzado:['#3a2f24','#100d08','#f0c8a0'],capanga:['#2c2838','#0c0a10','#c8a8e0'],comandante:['#2e352f','#0c0f0d','#d0c08f']
}
const fallback=(id)=>{const [a,b,c]=fallbackPalettes[id]; const variant=Object.keys(fallbackPalettes).indexOf(id); const cx=320+(variant%4)*55, cy=270+(variant%3)*35; return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 680"><defs><radialGradient id="g"><stop stop-color="${c}" stop-opacity=".82"/><stop offset=".36" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></radialGradient><filter id="f"><feGaussianBlur stdDeviation="22"/></filter></defs><rect width="800" height="680" fill="url(#g)"/><circle cx="170" cy="140" r="150" fill="${c}" opacity=".22" filter="url(#f)"/><circle cx="650" cy="520" r="180" fill="${c}" opacity=".14" filter="url(#f)"/><path d="M0 570 Q200 420 400 555 T800 490 V680 H0Z" fill="${b}" opacity=".6"/><path d="M0 120 L800 420 M0 300 L800 80 M0 510 L800 250" stroke="${c}" stroke-opacity=".14" stroke-width="2"/><g fill="none" stroke="${c}" stroke-width="5" stroke-linecap="round"><circle cx="${cx}" cy="${cy}" r="126" opacity=".72"/><circle cx="${cx}" cy="${cy}" r="98" opacity=".35"/><path d="M${cx} ${cy-160} L${cx+65} ${cy} L${cx} ${cy+160} L${cx-65} ${cy}Z" opacity=".82"/><path d="M${cx-140} ${cy}H${cx+140}M${cx} ${cy-140}V${cx} ${cy+140}" opacity=".4"/></g><circle cx="${cx}" cy="${cy}" r="13" fill="${c}"/></svg>`)}`}
const img=id=>generated[id] || fallback(id)

const c=(id,name,kind,source,attribute,complexity,role,description,why,attention,scene,image,score)=>({id,name,kind,source,attribute,complexity,role,description,why,attention,scene,image:img(id),imageAlt:`Retrato evocativo para ${name}`,score})
export const classes=[
c('guerreiro','Guerreiro','Classe básica','Jogo do Ano','Força','Baixa','Linha de frente','Um mestre de armas que transforma treino, coragem e aço em presença decisiva.', ['Você gosta de resolver conflitos cara a cara.','Sua resistência abre espaço para o grupo.'],'Brilha com uma arma favorita e decisões diretas.','“A ponte estreita. Você avança um passo — e ninguém passa.”','887827', {melee:5,defense:3,simple:4,precision:2}),
c('barbaro','Bárbaro','Classe básica','Jogo do Ano','Força','Baixa','Impacto','Fúria, coragem e instinto: o Bárbaro é a tempestade que chega antes do trovão.', ['Seu instinto puxa para o risco e a ação.','Você prefere impacto a sutileza.'],'A fúria pede posicionamento corajoso.','“Com o machado erguido, você ri para a tempestade.”','1552242',{melee:5,fury:5,nature:2,simple:4}),
c('bardo','Bardo','Classe básica','Jogo do Ano','Carisma','Média','Suporte','Canções, histórias e magia fazem do Bardo a faísca que une cada expedição.', ['Você fortalece pessoas e cenas sociais.','Flexibilidade é mais atraente que especialização.'],'Suas melhores jogadas nascem de apoiar o momento certo.','“Na taverna silenciosa, sua primeira nota faz os olhares voltarem.”','1763075',{support:5,social:5,magic:3,lead:2}),
c('bucaneiro','Bucaneiro','Classe básica','Jogo do Ano','Destreza','Média','Duelista','Um aventureiro elegante que aposta alto, luta com estilo e não teme o mar.', ['Você quer acrobacia, carisma e golpes precisos.','O risco é parte da diversão.'],'Funciona melhor quando há espaço para ousadia.','“O convés inclina; você sorri e salta sobre a lâmina inimiga.”','1001682',{melee:3,precision:5,sea:5,social:2,defense:1}),
c('cacador','Caçador','Classe básica','Jogo do Ano','Destreza','Média','Exploração','Conhece o ermo como uma velha trilha e encontra o alvo antes que ele perceba.', ['O ambiente é seu aliado natural.','Você gosta de perseguir e escolher o alvo.'],'Planejar a caçada aumenta muito seu impacto.','“A pegada se perde na chuva. Para você, ela acabou de começar.”','2387873',{ranged:5,nature:5,precision:4,companion:2,stealth:2}),
c('cavaleiro','Cavaleiro','Classe básica','Jogo do Ano','Força','Média','Defensor','Disciplina, honra e armadura: o Cavaleiro segura a linha quando todos precisam.', ['Proteger é tão importante quanto vencer.','Você aprecia ordem, dever e defesa.'],'Seu código e sua postura definem a história.','“O portão cede. Sua lança, não.”','163077',{defense:5,melee:3,lead:3,faith:1,tactics:2}),
c('clerigo','Clérigo','Classe básica','Jogo do Ano','Sabedoria','Média','Suporte divino','A fé manifesta milagres, proteção e respostas para quem caminha com propósito.', ['Você quer sustentar o grupo com propósito.','Fé e compaixão guiam suas decisões.'],'Escolha uma divindade que dê cor às suas escolhas.','“Sob as ruínas, sua prece acende uma luz que não vacila.”','208512',{faith:5,support:5,defense:2,magic:2}),
c('druida','Druida','Classe básica','Jogo do Ano','Sabedoria','Média','Natureza','Guardião dos ciclos vivos, capaz de assumir formas e chamar a força do mundo.', ['O ermo é mais interessante que a corte.','Você valoriza laços com criaturas e ciclos.'],'Sua conexão com a natureza orienta toda escolha.','“A mata prende a respiração; então responde ao seu chamado.”','957024',{nature:5,magic:3,companion:4,support:2,faith:1}),
c('arcanista','Arcanista','Classe básica','Jogo do Ano','Inteligência','Alta','Controle','Estudioso do impossível, molda magias para solucionar o que a espada não alcança.', ['Você gosta de ferramentas complexas e criativas.','Conhecimento é sua forma de aventura.'],'Exige atenção aos recursos, mas recompensa invenção.','“As runas no chão se erguem como constelações obedientes.”','1181671',{magic:5,complex:5,craft:2,tactics:3}),
c('inventor','Inventor','Classe básica','Jogo do Ano','Inteligência','Alta','Especialista','Onde outros veem sucata, o Inventor vê uma resposta ainda sem nome.', ['Você adora construir soluções inesperadas.','Preparação e engenho soam mais divertidos que força bruta.'],'Planejamento entre aventuras é parte do prazer.','“A engrenagem emperra uma vez. Na segunda, salva a expedição.”','3861969',{craft:5,complex:5,tactics:3,precision:2}),
c('ladino','Ladino','Classe básica','Jogo do Ano','Destreza','Média','Especialista','Silencioso, versátil e sempre um passo à frente da armadilha — ou da guarda.', ['Você prefere inteligência, precisão e discrição.','Quer resolver obstáculos fora do combate também.'],'Escolha os riscos: ousadia funciona melhor com plano.','“A fechadura suspira. Você já está do outro lado.”','1043474',{stealth:5,precision:5,dark:2,social:2,tactics:2}),
c('lutador','Lutador','Classe básica','Jogo do Ano','Força','Média','Combate desarmado','Seu próprio corpo é uma arma treinada para derrubar gigantes e desafiar limites.', ['Ação física e técnica são sua linguagem.','Você quer lutar sem depender de equipamento.'],'Mobilidade é seu melhor equipamento.','“Sem espada, sem medo: só o som dos seus passos na arena.”','1263349',{unarmed:5,melee:5,precision:3,simple:2}),
c('nobre','Nobre','Classe básica','Jogo do Ano','Carisma','Média','Liderança','Sua maior arma é inspirar, organizar e fazer com que todos acreditem no próximo passo.', ['Você vê potencial em cada aliado.','Liderança e influência importam para você.'],'Você brilha quando o grupo joga junto.','“O salão inteiro espera. Sua voz encontra a coragem deles.”','3771118',{lead:5,social:5,support:4,defense:1}),
c('paladino','Paladino','Classe básica','Jogo do Ano','Carisma','Média','Defensor divino','Um campeão de juramentos cuja fé transforma proteção em força luminosa.', ['Você quer unir combate, fé e proteção.','Grandes escolhas morais fazem parte do seu herói.'],'Seu juramento é uma promessa dramática, não só uma regra.','“Diante da sombra, seu juramento soa mais alto que o medo.”','2381069',{faith:5,defense:5,melee:3,lead:2,support:2}),
c('samurai','Samurai','Classe variante','Heróis de Arton','Força','Alta','Duelista','A disciplina da lâmina encontra a busca pelo golpe perfeito e pela honra pessoal.', ['Você busca técnica marcial e precisão.','Duelo e aperfeiçoamento são mais atraentes que muralhas.'],'Recompensa foco numa arma e decisões calculadas.','“A lâmina deixa a bainha; o mundo parece esperar o único corte.”','756790',{melee:5,precision:5,tactics:3,complex:3,defense:1}),
c('soldado','Soldado','Nova classe','Heróis de Arton','Força','Média','Tático','Treinado para agir em equipe, manter a cabeça fria e converter plano em vitória.', ['Você gosta de estratégia e formação.','A equipe é mais forte com direção clara.'],'A coordenação é sua assinatura em combate.','“Você aponta o flanco aberto. A companhia entende sem uma palavra.”','1638336',{tactics:5,lead:4,defense:3,melee:2,simple:2}),
c('mago','Mago','Classe variante','Dragão Brasil','Inteligência','Alta','Magia erudita','Um especialista ritualista que encontra padrões arcanos onde outros só veem caos.', ['Estudo profundo e magia versátil atraem você.','Você aceita complexidade em troca de possibilidades.'],'Prepare seus feitiços como quem prepara um mapa.','“Na torre abandonada, você lê a poeira como um pergaminho.”','1117132',{magic:5,complex:5,tactics:2,craft:2}),
c('feiticeiro','Feiticeiro','Classe variante','Dragão Brasil','Carisma','Média','Magia inata','A magia corre no sangue, viva e pessoal, respondendo à sua presença e imaginação.', ['Você quer poder mágico com presença pessoal.','Improvisar parece melhor que decorar fórmulas.'],'Sua origem é uma excelente porta para a narrativa.','“A luz em suas mãos não foi aprendida. Ela sempre esteve lá.”','948873',{magic:5,social:3,complex:3,dark:1}),
c('bruxo','Bruxo','Classe variante','Dragão Brasil','Inteligência','Alta','Magia ritual','Pactos, fórmulas e um foco singular: poder arcano com textura de mistério.', ['Você gosta de rituais, segredos e preparação.','Quer uma magia com identidade incomum.'],'Seu foco arcano merece protagonismo na história.','“O caldeirão borbulha; a resposta surge na fumaça verde.”','846741',{magic:5,complex:4,craft:3,dark:3}),
c('medico','Médico de Salistick','Nova classe','Heróis de Arton','Inteligência','Média','Suporte','Conhecimento, instrumentos e sangue-frio para salvar vidas no instante impossível.', ['Você quer apoio prático e decisões rápidas.','Cuidar do grupo é sua forma de heroísmo.'],'Você vence batalhas fazendo os outros permanecerem de pé.','“O caos ruge ao redor. Suas mãos, porém, não tremem.”','5327585',{support:5,craft:4,complex:3,tactics:2}),
c('místico','Místico','Nova classe','Dragão Brasil','Sabedoria','Alta','Espiritual','Vozes ancestrais e forças sutis acompanham quem enxerga além do véu comum.', ['Você se interessa pelo espiritual e pelo estranho.','Quer magia guiada por intuição e propósito.'],'Sua ligação mística pede espaço na narrativa.','“No silêncio do templo, os ancestrais finalmente respondem.”','597909',{magic:4,faith:4,complex:4,support:2,nature:1}),
c('pirata','Pirata','Classe variante','Dragão Brasil','Carisma','Média','Aventura marítima','Entre mapas rasgados e mares revoltos, transforma liberdade e ousadia em sobrevivência.', ['Você quer aventura livre, mar e personalidade.','Seu grupo pode ser uma tripulação.'],'Brilha em campanhas com viagem, risco e improviso.','“O horizonte é uma promessa. Você ergue a vela para cobrá-la.”','1008409',{sea:5,social:4,melee:2,precision:2,lead:2}),
c('treinador','Treinador','Classe especial','Heróis de Arton','Carisma','Média','Comando de criaturas','Há vínculos que nenhum comando pode forjar. O maior companheiro não obedece — escolhe lutar ao seu lado.', ['Criaturas e companheiros são a sua vocação.','Você gosta de liderar quem não fala — e entender mesmo assim.'],'Sua força cresce com o vínculo com sua criatura; cultive-o a cada aventura.','“Não quero uma fera obediente. Quero que ela escolha lutar ao meu lado.”','5001142',{companion:5,lead:4,nature:3,support:2,tactics:2}),
c('frade','Frade','Classe variante','Deuses e Heróis','Sabedoria','Média','Fé humilde','Despojado e devoto, o Frade leva a fé sem armadura — e a proteção divina aonde o luxo não entra.', ['Você valoriza a simplicidade e o serviço.','Fé sem aparato, perto das pessoas, combina com você.'],'Suas bênçãos brilham na simplicidade; evite depender de equipamento.','“Com uma veste simples e uma prece, você enfrenta a noite.”','5001243',{faith:5,support:4,simple:4,social:2,unarmed:2}),
c('necromante','Necromante','Classe variante','Heróis de Arton','Inteligência','Alta','Magia das sombras','Onde a morte sussurra, o Necromante responde: domínio sobre o limiar que os vivos temem atravessar.', ['Você gosta de temas sombrios e poder arcano.','Comandar os caídos é um desafio que atrai você.'],'Sua arte assusta aliados; a narrativa precisa abrir espaço para ela.','“A terra se move devagar. Então se ergue, obediente.”','5001344',{dark:5,magic:5,complex:4,craft:2}),
c('machado-pedra','Machado de Pedra','Classe variante','Heróis de Arton','Força','Baixa','Impacto bruto','Um Bárbaro que troca o aço pela rocha: golpes que racham muralhas e lendas.', ['Você quer dano colossal e visual primitivo.','O corpo a corpo brutal é a sua praia.'],'Sua arma é pesada e lenta; escolha bem o instante do golpe.','“A muralha treme. O machado de pedra, não.”','5001445',{melee:5,fury:5,simple:4,defense:1,nature:1}),
c('magimarcialista','Magimarcialista','Classe variante','Heróis de Arton','Carisma','Alta','Bardo de batalha','Lâmina numa mão, canção na outra: o Magimarcialista dança entre a plateia e a batalha.', ['Você quer unir arte e combate no mesmo personagem.','Versatilidade mágica com presença marcial atrai você.'],'Dividir o foco entre magia e lâmina exige gestão cuidadosa.','“Cada acorde afia a lâmina; cada golpe marca o ritmo.”','5001546',{magic:4,melee:4,support:3,social:3,complex:3}),
c('duelista','Duelista','Classe variante','Heróis de Arton','Destreza','Média','Esgrima elegante','Um Bucaneiro que afia a elegância até o fio da lâmina: duelos, apostas e um floreio mortal.', ['Você adora combates de um contra um.','Estilo, provocação e precisão são a sua assinatura.'],'Brilha no duelo; em campo aberto, precisa de mobilidade.','“Você saúda com a lâmina. O duelo começa — e termina.”','5001647',{precision:5,melee:4,social:3,sea:2,defense:1}),
c('seteiro','Seteiro','Classe variante','Heróis de Arton','Destreza','Média','Atirador de elite','O Caçador que fez do arco uma extensão do olhar: a flecha encontra o que os olhos apontam.', ['A distância é o seu território.','Precisão e paciência definem seu estilo.'],'Precisa de alcance; combates fechados pedem um plano B.','“A corda canta uma vez. O alvo, do outro lado do vale, tomba.”','5001748',{ranged:5,precision:5,nature:3,stealth:2,simple:2}),
c('vassalo','Vassalo','Classe variante','Heróis de Arton','Força','Média','Escudeiro leal','A serviço de um senhor, o Vassalo converte dever em muralha e juramento em vitória.', ['Você gosta de servir a uma causa maior.','Lealdade e proteção estruturam o seu herói.'],'Sua história pede um senhor ou ideal bem definido.','“O juramento pesa na espada — e a sustenta.”','5001849',{defense:4,lead:3,support:3,melee:2,tactics:2}),
c('usurpador','Usurpador','Classe variante','Heróis de Arton','Sabedoria','Alta','Fé corrompida','Um Clérigo que reivindica o divino por conta própria, dobrando o sagrado até que ele responda.', ['Tensões entre fé e poder fascinam você.','Um herói ambíguo com milagres próprios atrai você.'],'Sua relação com os deuses é tensa; a mesa precisa curtir o conflito.','“O altar reconhece a sua voz — mesmo contra a vontade dele.”','5001950',{faith:4,dark:4,social:3,complex:3,magic:2}),
c('ermitao','Ermitão','Classe variante','Heróis de Arton','Sabedoria','Média','Sábio da natureza','Longe da corte, o Ermitão guarda os segredos do mato: raízes, silêncio e o ciclo das estações.', ['O isolamento e a simplicidade ressoam em você.','Sabedoria da natureza sem pressa combina com o seu ritmo.'],'Você brilha fora da cidade; prepare-se para o concreto.','“A mata não fala com estranhos. Com você, conversa.”','5002051',{nature:5,faith:3,simple:4,support:2,companion:2}),
c('inovador','Inovador','Classe variante','Heróis de Arton','Inteligência','Alta','Tática engenhosa','Um Guerreiro que vence antes da batalha: engenhocas, planos e uma mente afiada como o aço.', ['Estratégia e preparação são o seu forte.','Você quer um combatente que também pensa.'],'Suas invenções pedem tempo e recursos entre os combates.','“O campo minado que você montou na véspera resolve a guerra.”','5002152',{craft:4,tactics:5,melee:2,complex:3,lead:2}),
c('alquimista','Alquimista','Classe variante','Heróis de Arton','Inteligência','Alta','Ciência arcana','Frascos, fórmulas e fogo: o Alquimista destila o impossível em doses precisas.', ['Você adora poções, bombas e reações.','Ciência com sabor de magia é o seu jogo.'],'Administre os ingredientes; a bolsa do alquimista é o seu grimório.','“O frasco rola devagar. A explosão, não.”','5002253',{craft:5,magic:3,complex:4,support:2,tactics:2}),
c('ventanista','Ventanista','Classe variante','Heróis de Arton','Destreza','Média','Velocidade e furtividade','Um Ladino que se move como o vento: invisível entre telhados, inevitável em silêncio.', ['Rapidez e furtividade são o seu estilo.','A cidade alta e os seus segredos chamam você.'],'Sua mobilidade depende de espaço e verticalidade.','“A rajada apaga as velas. Quando voltam, você já não está.”','5002354',{stealth:5,precision:4,tactics:2,social:2,dark:2}),
c('atleta','Atleta','Classe variante','Heróis de Arton','Força','Baixa','Físico imbatível','Um Lutador no auge da forma: músculo, técnica e a multidão gritando o seu nome.', ['Corpo em movimento é a sua fantasia.','Combate físico puro, sem armaduras pesadas, atrai você.'],'Sua força mora na mobilidade; evite ser imobilizado.','“A arena prende a respiração quando você se agacha para o salto.”','5002455',{unarmed:5,melee:4,precision:3,simple:3,social:1}),
c('burgues','Burguês','Classe variante','Heróis de Arton','Carisma','Média','Influência e riqueza','Um Nobre que troca o sangue azul pelo ouro vivo: contratos, favores e uma rede que vale um reino.', ['Dinheiro e influência são armas que você quer usar.','Negociação e bastidores divertem mais do que a guerra.'],'Sua rede social é o seu poder; mantenha os contatos vivos.','“A assinatura no pergaminho move exércitos.”','5002556',{social:5,lead:3,craft:2,support:3,complex:2}),
c('santo','Santo','Classe variante','Heróis de Arton','Carisma','Média','Fé luminosa','Um Paladino tocado pelo divino: a luz não o segue — ela o antecede.', ['O arquétipo do escolhido luminoso é o seu favorito.','Milagres visíveis e presença sagrada combinam com você.'],'Grandes poderes trazem grandes expectativas — e provações.','“A praça se cala quando a luz começa a sair de você.”','5002657',{faith:5,defense:3,support:3,social:3,lead:2}),
c('sentinela','Sentinela','Classe variante','Dragão Brasil','Inteligência','Alta','Magia protetora','Um Arcanista que levanta muros de mana e barreiras vivas: o escudo invisível do grupo.', ['Proteção arcana é a sua vocação.','Você prefere conter ameaças a destruí-las.'],'Suas defesas exigem preparo e leitura do campo.','“O feitiço inimigo se estilhaça contra o ar — no ar.”','5002758',{magic:5,defense:4,tactics:3,complex:3,craft:1}),
c('miragem','Miragem','Classe variante','Dragão Brasil','Destreza','Média','Ilusão e emboscada','Um Caçador que ataca onde o deserto mente: cada duna esconde um tiro que não se vê chegar.', ['Ilusões e emboscadas são a sua arte.','Paciência de predador combina com você.'],'Funciona melhor com terreno e tempo para armar a caçada.','“O oásis tremula. Você atira do lugar onde ele não está.”','5002859',{stealth:4,ranged:4,precision:4,dark:2,nature:2}),
c('cruzado','Cruzado','Classe variante','Dragão Brasil','Força','Média','Fé em armas','Um Clérigo de armadura e martelo: a palavra divina chega a cavalo, com estandarte e fúria santa.', ['Você quer fé que avança em formação.','Combate e milagre no mesmo personagem atraem você.'],'Sua causa pede clareza: contra o quê você marcha?','“O estandarte se ergue. A carga sagrada começa.”','5002960',{faith:4,melee:4,defense:3,lead:2,tactics:2}),
c('capanga','Capanga','Classe variante','Dragão Brasil','Destreza','Baixa','Trabalho sujo','Um Ladino dos becos e das dívidas: mãos rápidas, lealdade comprada e nenhuma pergunta.', ['Personagens de submundo e moral cinzenta atraem você.','Resolver problemas do jeito prático é o seu estilo.'],'Sua fama precede suas boas intenções — se existirem.','“O beco conhece o seu apelido. E os devedores, o seu preço.”','5003061',{stealth:4,melee:3,dark:4,social:2,precision:2}),
c('comandante','Comandante','Classe variante','Dragão Brasil','Carisma','Média','Estratégia de campo','Um Nobre que troca o salão pelo mapa de guerra: ordens claras, tropas fiéis e a vitória planejada.', ['Liderar exércitos é a sua fantasia.','Táticas e moral de tropa são o seu forte.'],'Você depende do grupo; liderar é melhor que fazer sozinho.','“Sua voz corta o caos. O flanco esquerdo, enfim, avança.”','5003162',{lead:5,tactics:5,social:3,defense:2,support:2})
]
