import guerreiroImage from './assets/guerreiro.png'
import barbaroImage from './assets/barbaro.png'
import bardoImage from './assets/bardo.png'
import bucaneiroImage from './assets/bucaneiro.png'
import cacadorImage from './assets/cacador.png'
import cavaleiroImage from './assets/cavaleiro.png'
import clerigoImage from './assets/clerigo.png'
import druidaImage from './assets/druida.png'
import arcanistaImage from './assets/arcanista.png'
import inventorImage from './assets/inventor.png'
import ladinoImage from './assets/ladino.png'
import lutadorImage from './assets/lutador.png'
import nobreImage from './assets/nobre.png'
import paladinoImage from './assets/paladino.png'
import samuraiImage from './assets/samurai.png'
import soldadoImage from './assets/soldado.png'
import magoImage from './assets/mago.png'
import feiticeiroImage from './assets/feiticeiro.png'
import bruxoImage from './assets/bruxo.png'
import medicoImage from './assets/medico.png'
import misticoImage from './assets/mistico.png'
import pirataImage from './assets/pirata.png'

const generated = { guerreiro: guerreiroImage, barbaro: barbaroImage, bardo: bardoImage, bucaneiro: bucaneiroImage, cacador: cacadorImage, cavaleiro: cavaleiroImage, clerigo: clerigoImage, druida: druidaImage, arcanista: arcanistaImage, inventor: inventorImage, ladino: ladinoImage, lutador: lutadorImage, nobre: nobreImage, paladino: paladinoImage, samurai: samuraiImage, soldado: soldadoImage, mago: magoImage, feiticeiro: feiticeiroImage, bruxo: bruxoImage, medico: medicoImage, místico: misticoImage, pirata: pirataImage }
const fallbackPalettes = {
  ladino:['#15242a','#071012','#d2a15a'],lutador:['#3b2118','#120b08','#ebae59'],nobre:['#36212d','#120d12','#dbb56c'],paladino:['#3d3217','#12100a','#fff0a1'],samurai:['#421f1e','#13090a','#e1a45d'],soldado:['#293128','#0c100b','#d5ab65'],mago:['#1f2444','#080a18','#a9bcff'],feiticeiro:['#3c1831','#140713','#ef8a88'],bruxo:['#16372c','#07120d','#86e699'],medico:['#29333a','#0a1012','#d3c3a4'],místico:['#282143','#0e0a18','#bda5ff'],pirata:['#153442','#071014','#e5b55b']
}
const fallback=(id)=>{const [a,b,c]=fallbackPalettes[id]; const variant=Object.keys(fallbackPalettes).indexOf(id); const cx=320+(variant%4)*55, cy=270+(variant%3)*35; return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 680"><defs><radialGradient id="g"><stop stop-color="${c}" stop-opacity=".82"/><stop offset=".36" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></radialGradient><filter id="f"><feGaussianBlur stdDeviation="22"/></filter></defs><rect width="800" height="680" fill="url(#g)"/><circle cx="170" cy="140" r="150" fill="${c}" opacity=".22" filter="url(#f)"/><circle cx="650" cy="520" r="180" fill="${c}" opacity=".14" filter="url(#f)"/><path d="M0 570 Q200 420 400 555 T800 490 V680 H0Z" fill="${b}" opacity=".6"/><path d="M0 120 L800 420 M0 300 L800 80 M0 510 L800 250" stroke="${c}" stroke-opacity=".14" stroke-width="2"/><g fill="none" stroke="${c}" stroke-width="5" stroke-linecap="round"><circle cx="${cx}" cy="${cy}" r="126" opacity=".72"/><circle cx="${cx}" cy="${cy}" r="98" opacity=".35"/><path d="M${cx} ${cy-160} L${cx+65} ${cy} L${cx} ${cy+160} L${cx-65} ${cy}Z" opacity=".82"/><path d="M${cx-140} ${cy}H${cx+140}M${cx} ${cy-140}V${cx} ${cy+140}" opacity=".4"/></g><circle cx="${cx}" cy="${cy}" r="13" fill="${c}"/></svg>`)}`}
const img=id=>generated[id] || fallback(id)

const c=(id,name,kind,source,attribute,complexity,role,description,why,attention,scene,image,score)=>({id,name,kind,source,attribute,complexity,role,description,why,attention,scene,image:img(id),imageAlt:`Retrato evocativo para ${name}`,score})
export const classes=[
c('guerreiro','Guerreiro','Classe básica','Jogo do Ano','Força','Baixa','Linha de frente','Um mestre de armas que transforma treino, coragem e aço em presença decisiva.', ['Você gosta de resolver conflitos cara a cara.','Sua resistência abre espaço para o grupo.'],'Brilha com uma arma favorita e decisões diretas.','“A ponte estreita. Você avança um passo — e ninguém passa.”','887827', {melee:5,defense:3,simple:4,precision:2}),
c('barbaro','Bárbaro','Classe básica','Jogo do Ano','Força','Baixa','Impacto','Fúria, coragem e instinto: o Bárbaro é a tempestade que chega antes do trovão.', ['Seu instinto puxa para o risco e a ação.','Você prefere impacto a sutileza.'],'A fúria pede posicionamento corajoso.','“Com o machado erguido, você ri para a tempestade.”','1552242',{melee:5,fury:5,nature:2,simple:4}),
c('bardo','Bardo','Classe básica','Jogo do Ano','Carisma','Média','Suporte','Canções, histórias e magia fazem do Bardo a faísca que une cada expedição.', ['Você fortalece pessoas e cenas sociais.','Flexibilidade é mais atraente que especialização.'],'Suas melhores jogadas nascem de apoiar o momento certo.','“Na taverna silenciosa, sua primeira nota faz os olhares voltarem.”','1763075',{support:5,social:5,magic:3,lead:2}),
c('bucaneiro','Bucaneiro','Classe básica','Jogo do Ano','Destreza','Média','Duelista','Um aventureiro elegante que aposta alto, luta com estilo e não teme o mar.', ['Você quer acrobacia, carisma e golpes precisos.','O risco é parte da diversão.'],'Funciona melhor quando há espaço para ousadia.','“O convés inclina; você sorri e salta sobre a lâmina inimiga.”','1001682',{melee:3,precision:5,sea:5,social:2,defense:1}),
c('cacador','Caçador','Classe básica','Jogo do Ano','Destreza','Média','Exploração','Conhece o ermo como uma velha trilha e encontra o alvo antes que ele perceba.', ['O ambiente é seu aliado natural.','Você gosta de perseguir e escolher o alvo.'],'Planejar a caçada aumenta muito seu impacto.','“A pegada se perde na chuva. Para você, ela acabou de começar.”','2387873',{ranged:5,nature:5,precision:4,companion:2,stealth:2}),
c('cavaleiro','Cavaleiro','Classe básica','Jogo do Ano','Força','Média','Defensor','Disciplina, honra e armadura: o Cavaleiro segura a linha quando todos precisam.', ['Proteger é tão importante quanto vencer.','Você aprecia ordem, dever e defesa.'],'Seu código e sua postura definem a história.','“O portão cede. Sua lança, não.”','163077',{defense:5,melee:3,lead:3,faith:1,tactics:2}),
c('clerigo','Clérigo','Classe básica','Jogo do Ano','Sabedoria','Média','Suporte divino','A fé manifesta milagres, proteção e respostas para quem caminha com propósito.', ['Você quer sustentar o grupo com propósito.','Fé e compaixão guiam suas decisões.'],'Escolha uma divindade que dê cor às suas escolhas.','“Sob as ruínas, sua prece acende uma luz que não vacila.”','208512',{faith:5,support:5,defense:2,magic:2}),
c('druida','Druida','Classe básica','Jogo do Ano','Sabedoria','Média','Natureza','Guardião dos ciclos vivos, capaz de assumir formas e chamar a força do mundo.', ['O ermo é mais interessante que a corte.','Você valoriza laços com criaturas e ciclos.'],'Sua conexão com a natureza orienta toda escolha.','“A mata prende a respiração; então responde ao seu chamado.”','957024',{nature:5,magic:3,companion:4,support:2,faith:1}),
c('arcanista','Arcanista','Classe básica','Jogo do Ano','Inteligência','Alta','Controle','Estudioso do impossível, molda magias para solucionar o que a espada não alcança.', ['Você gosta de ferramentas complexas e criativas.','Conhecimento é sua forma de aventura.'],'Exige atenção aos recursos, mas recompensa invenção.','“As runas no chão se erguem como constelações obedientes.”','1181671',{magic:5,complex:5,craft:2,tactics:3}),
c('inventor','Inventor','Classe básica','Jogo do Ano','Inteligência','Alta','Especialista','Onde outros veem sucata, o Inventor vê uma resposta ainda sem nome.', ['Você adora construir soluções inesperadas.','Preparação e engenho soam mais divertidos que força bruta.'],'Planejamento entre aventuras é parte do prazer.','“A engrenagem emperra uma vez. Na segunda, salva a expedição.”','3861969',{craft:5,complex:5,tactics:3,precision:2}),
c('ladino','Ladino','Classe básica','Jogo do Ano','Destreza','Média','Especialista','Silencioso, versátil e sempre um passo à frente da armadilha — ou da guarda.', ['Você prefere inteligência, precisão e discrição.','Quer resolver obstáculos fora do combate também.'],'Escolha os riscos: ousadia funciona melhor com plano.','“A fechadura suspira. Você já está do outro lado.”','1043474',{stealth:5,precision:5,dark:2,social:2,tactics:2}),
c('lutador','Lutador','Classe básica','Jogo do Ano','Força','Média','Combate desarmado','Seu próprio corpo é uma arma treinada para derrubar gigantes e desafiar limites.', ['Ação física e técnica são sua linguagem.','Você quer lutar sem depender de equipamento.'],'Mobilidade é seu melhor equipamento.','“Sem espada, sem medo: só o som dos seus passos na arena.”','1263349',{unarmed:5,melee:5,precision:3,simple:2}),
c('nobre','Nobre','Classe básica','Jogo do Ano','Carisma','Média','Liderança','Sua maior arma é inspirar, organizar e fazer com que todos acreditem no próximo passo.', ['Você vê potencial em cada aliado.','Liderança e influência importam para você.'],'Você brilha quando o grupo joga junto.','“O salão inteiro espera. Sua voz encontra a coragem deles.”','3771118',{lead:5,social:5,support:4,defense:1}),
c('paladino','Paladino','Classe básica','Jogo do Ano','Carisma','Média','Defensor divino','Um campeão de juramentos cuja fé transforma proteção em força luminosa.', ['Você quer unir combate, fé e proteção.','Grandes escolhas morais fazem parte do seu herói.'],'Seu juramento é uma promessa dramática, não só uma regra.','“Diante da sombra, seu juramento soa mais alto que o medo.”','2381069',{faith:5,defense:5,melee:3,lead:2,support:2}),
c('samurai','Samurai','Classe variante','Heróis de Arton','Força','Alta','Duelista','A disciplina da lâmina encontra a busca pelo golpe perfeito e pela honra pessoal.', ['Você busca técnica marcial e precisão.','Duelo e aperfeiçoamento são mais atraentes que muralhas.'],'Recompensa foco numa arma e decisões calculadas.','“A lâmina deixa a bainha; o mundo parece esperar o único corte.”','756790',{melee:5,precision:5,tactics:3,complex:3,defense:1}),
c('soldado','Soldado','Nova classe','Heróis de Arton','Força','Média','Tático','Treinado para agir em equipe, manter a cabeça fria e converter plano em vitória.', ['Você gosta de estratégia e formação.','A equipe é mais forte com direção clara.'],'A coordenação é sua assinatura em combate.','“Você aponta o flanco aberto. A companhia entende sem uma palavra.”','1638336',{tactics:5,lead:4,defense:3,melee:2,simple:2}),
c('mago','Mago','Classe variante','Dragão Brasil','Inteligência','Alta','Magia erudita','Um especialista ritualista que encontra padrões arcanos onde outros só veem caos.', ['Estudo profundo e magia versátil atraem você.','Você aceita complexidade em troca de possibilidades.'],'Prepare seus feitiços como quem prepara um mapa.','“Na torre abandonada, você lê a poeira como um pergaminho.”','1117132',{magic:5,complex:5,tactics:2,craft:2}),
c('feiticeiro','Feiticeiro','Classe variante','Dragão Brasil','Carisma','Média','Magia inata','A magia corre no sangue, viva e pessoal, respondendo à sua presença e imaginação.', ['Você quer poder mágico com presença pessoal.','Improvisar parece melhor que decorar fórmulas.'],'Sua origem é uma excelente porta para a narrativa.','“A luz em suas mãos não foi aprendida. Ela sempre esteve lá.”','948873',{magic:5,social:3,complex:3,dark:1}),
c('bruxo','Bruxo','Classe variante','Dragão Brasil','Inteligência','Alta','Magia ritual','Pactos, fórmulas e um foco singular: poder arcano com textura de mistério.', ['Você gosta de rituais, segredos e preparação.','Quer uma magia com identidade incomum.'],'Seu foco arcano merece protagonismo na história.','“O caldeirão borbulha; a resposta surge na fumaça verde.”','846741',{magic:5,complex:4,craft:3,dark:3}),
c('medico','Médico de Salistick','Nova classe','Heróis de Arton','Inteligência','Média','Suporte','Conhecimento, instrumentos e sangue-frio para salvar vidas no instante impossível.', ['Você quer apoio prático e decisões rápidas.','Cuidar do grupo é sua forma de heroísmo.'],'Você vence batalhas fazendo os outros permanecerem de pé.','“O caos ruge ao redor. Suas mãos, porém, não tremem.”','5327585',{support:5,craft:4,complex:3,tactics:2}),
c('místico','Místico','Nova classe','Dragão Brasil','Sabedoria','Alta','Espiritual','Vozes ancestrais e forças sutis acompanham quem enxerga além do véu comum.', ['Você se interessa pelo espiritual e pelo estranho.','Quer magia guiada por intuição e propósito.'],'Sua ligação mística pede espaço na narrativa.','“No silêncio do templo, os ancestrais finalmente respondem.”','597909',{magic:4,faith:4,complex:4,support:2,nature:1}),
c('pirata','Pirata','Classe variante','Dragão Brasil','Carisma','Média','Aventura marítima','Entre mapas rasgados e mares revoltos, transforma liberdade e ousadia em sobrevivência.', ['Você quer aventura livre, mar e personalidade.','Seu grupo pode ser uma tripulação.'],'Brilha em campanhas com viagem, risco e improviso.','“O horizonte é uma promessa. Você ergue a vela para cobrá-la.”','1008409',{sea:5,social:4,melee:2,precision:2,lead:2})
]
