const q=(id,short,prompt,context,options)=>({id,short,prompt,context,options})
const o=(title,detail,score)=>({title,detail,score})
export const questions = [
q('scene','Cena','Que cena faz seus olhos brilharem na mesa?','Escolha o momento que você quer viver primeiro.',[
o('Duelo decisivo','Aço, coragem e um oponente à altura.',{melee:4,defense:2,precision:2}),o('Mistério arcano','Runas, segredos e magia que muda tudo.',{magic:5,complex:2,craft:1}),o('Resgate heróico','Proteger aliados quando tudo desaba.',{support:3,faith:2,lead:2,defense:2}),o('Caçada no ermo','Rastros, silêncio e a presa certa.',{nature:4,ranged:2,stealth:2})]),
q('position','Posição','Onde você prefere estar quando a luta começa?','Seu lugar também conta uma história.',[
o('Na linha de frente','Recebendo o impacto e abrindo espaço.',{melee:4,defense:3,fury:1}),o('No ponto alto','Observando e escolhendo o disparo.',{ranged:4,precision:3,stealth:1}),o('Entre os aliados','Coordenando, curando, inspirando.',{support:4,lead:2,faith:2}),o('Onde ninguém espera','Flanqueando e mudando o tabuleiro.',{stealth:4,tactics:3,precision:1})]),
q('power','Poder','De onde vem a força do seu herói?','Confie no impulso que parece mais seu.',[
o('Disciplina e treino','Meu corpo e minha técnica são a arma.',{melee:3,unarmed:2,precision:2,simple:1}),o('Mistério e estudo','Conhecimento é poder quando bem usado.',{magic:5,complex:3,craft:1}),o('Fé e propósito','Uma causa maior guia meus passos.',{faith:5,support:2,defense:1}),o('Instinto indomável','A natureza e a fúria não pedem licença.',{nature:3,fury:3,companion:1})]),
q('company','Companhia','Que companhia parece mais natural?','Pense na mesa e também no mundo.',[
o('Um bando leal','Lealdade, brindes e boas histórias.',{social:3,lead:2,support:2,sea:1}),o('Um mentor e livros','Perguntas difíceis e respostas antigas.',{magic:3,complex:3,craft:2}),o('Uma criatura parceira','Laços que sobrevivem ao perigo.',{companion:5,nature:2,ranged:1}),o('Uma ordem ou legião','Dever, formação e estratégia.',{defense:3,lead:3,tactics:3})]),
q('depth','Profundidade','Quanta complexidade você quer dominar?','Não há resposta errada — só o seu ritmo.',[
o('Direto ao ponto','Quero entrar em ação logo.',{simple:5,melee:2}),o('Camadas na medida','Gosto de escolhas táticas claras.',{tactics:3,precision:2,complex:1}),o('Muitas combinações','Quero construir soluções improváveis.',{complex:5,magic:2,craft:2}),o('Narrativa primeiro','Quero brilhar nas relações e cenas.',{social:4,support:2,lead:2})]),
q('ambush','Emboscada','Uma caravana é atacada ao entardecer. Sua reação?','Há civis, pouco tempo e inimigos escondidos.',[
o('Ergo a guarda','Viro a muralha entre o perigo e os civis.',{defense:5,melee:2,lead:1}),o('Acho o atirador','Uso terreno e precisão para quebrar a emboscada.',{ranged:3,precision:3,stealth:2}),o('Mudo o campo','Uma magia bem colocada resolve a situação.',{magic:4,tactics:3,complex:1}),o('Guio todos à saída','Organizo a fuga e mantenho o grupo unido.',{support:3,lead:4,social:1})]),
q('city','Cidade','Em Valkaria, você busca uma informação crucial.','A cidade grande esconde respostas em toda esquina.',[
o('Converso nas tavernas','A pista certa está com as pessoas.',{social:5,lead:1,support:1}),o('Sigo pelas sombras','Quem não quer ser visto vê mais.',{stealth:5,precision:2,dark:1}),o('Visito bibliotecas','Arquivos e rituais têm memória longa.',{magic:3,complex:3,craft:1}),o('Aciono contatos oficiais','Hierarquia e reputação abrem portas.',{lead:3,defense:2,tactics:2})]),
q('wild','Ermo','Perdidos no ermo há três dias, o que faz?','A sobrevivência revela instintos.',[
o('Leio a floresta','Rastros, água e abrigo estão à vista.',{nature:5,companion:1,precision:1}),o('Improviso ferramentas','Transformo restos em uma solução.',{craft:5,complex:2,tactics:1}),o('Invoco ajuda','Há forças antigas que podem responder.',{magic:3,faith:2,nature:2}),o('Mantenho o ânimo','Ninguém fica para trás.',{support:3,lead:3,defense:1})]),
q('moral','Dilema','O vilão se rende. O que você faz?','Sua decisão deixará marcas na aventura.',[
o('Entrego à justiça','Leis e promessas importam.',{defense:2,lead:2,faith:2,social:1}),o('Procuro a verdade','Há algo que ele ainda não contou.',{social:3,magic:2,tactics:2}),o('Não baixo a guarda','Bondade não é descuido.',{precision:2,stealth:2,dark:1,defense:1}),o('Ofereço redenção','Uma escolha pode mudar um destino.',{faith:3,support:3,lead:1})]),
q('weapon','Ferramenta','Se tivesse uma única ferramenta, qual seria?','A resposta diz muito sobre seu estilo.',[
o('Lâmina ancestral','Uma extensão da minha vontade.',{melee:5,precision:2}),o('Arco ou besta','Distância, paciência e impacto.',{ranged:5,precision:3}),o('Grimório ou foco','Palavras que reescrevem o impossível.',{magic:5,complex:2}),o('Kit engenhoso','Sempre há uma peça que pode ajudar.',{craft:5,tactics:2,simple:1})]),
q('tone','Tom','Qual tom você quer para a aventura?','Escolha a emoção que quer perseguir.',[
o('Épico e honrado','Juramentos, bandeiras e grandes feitos.',{lead:3,defense:3,faith:2}),o('Sombrio e sagaz','Segredos, riscos e vitórias discretas.',{dark:4,stealth:3,precision:1}),o('Selvagem e livre','Tempestades, feras e horizontes abertos.',{nature:4,fury:2,sea:2}),o('Estranho e fantástico','O impossível é só o começo.',{magic:4,complex:3,craft:1})]),
q('party','Grupo','Qual papel você assume no grupo?','A última peça da sua bússola.',[
o('Escudo do grupo','Eu seguro a linha.',{defense:5,melee:2,lead:1}),o('Especialista','Eu resolvo o que ninguém mais resolve.',{precision:3,stealth:2,craft:2,tactics:2}),o('Coração do grupo','Eu sustento, inspiro e curo.',{support:5,faith:2,social:1}),o('Força imprevisível','Eu crio a abertura que muda a batalha.',{magic:3,fury:2,ranged:1,complex:2})])
]
